#
# RPITalk Configuration
#
# This file controls which hardware synth the Pi will emulate, which
# port it listens on, and  the debug level.
#
[RPITalk]

# TheID of the hardware synth to emulate
# dectlk  for DECtalk Express
# ltlk for LiteTalk
emulate = dectlk

# The port to listen on
# ttyGS0 if you are using the Raspberry Pi OTG port
# ttyUSB0 if you are using a USB-serial converter
# ttyS0 if you  are running this on a machine with a built-in serial port
port = ttyGS0

# Debug verbosity level
# 0 sets logging level to warning
# 1 sets logging level to info
# 2 sets logging level to debug
# 3 sets logging level to debug plus prints a whole lot of other stuff
debug = 0

# EOF
